### PR TITLE
Infrastructure update

### LINKED ISSUE #4: ``python setup.py egg_info`` should work without the dependencies installed
As far as I understand this should work, but the test fail on travis. If this is not the case for ``sdpy``, then the test run should be removed from the ``.travis.yml`` file.

```
Could not locate requirements.txt. Override the install: key in your .travis.yml to install dependencies.
0.48s$ python setup.py $SETUP_CMD
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    __import__(PACKAGENAME)
  File "/home/travis/build/keflavich/sdpy/sdpy/__init__.py", line 1, in <module>
    from . import makecube
  File "/home/travis/build/keflavich/sdpy/sdpy/makecube.py", line 6, in <module>
    import pyfits
ImportError: No module named pyfits
```

### PR DESCRIPTION
**Pull request by bsipocz**
DO not merge yet.

Including:

  -  updating ``astropy-helpers`` to 1.0.5
  -  opting in ``ci-helpers`` with travis
  -  opting in the container based travis
  - completing the package setup by copying over the missing part from ``package-template``
  - adding very basic index.rst to make sphinx pass
  - some docstring clean up to get rid of sphinx warnings

Closes #4

### CODE REVIEW

**Comment by bsipocz** [comment]
@keflavich - This one is not running travis, either.

**Comment by keflavich** [comment]
@bsipocz I turned it on just before you committed.  However, there are no tests!

**Comment by bsipocz** [comment]
Haha, even without tests there are some problems. I saw this locally, too when tried ``python setup.py develop``

**Comment by bsipocz** [comment]
@keflavich - this should pass now, so ready for review and merge.

**Comment by keflavich** [comment]
Thanks @bsipocz, this is a huge help!

**Pull request merged**
